# Generated by Django 3.0.3 on 2020-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200221_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='descrpition',
            new_name='description',
        ),
    ]
