# Generated by Django 3.0.3 on 2020-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_saleitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
